image: debian:stable

stages:
  - deps
  - build

cache:
  key: toolchain
  paths:
    - w64-mingw32-sysroot/
    - EASTL-build/libEASTL.a
    - EASTL-native-build/libEASTL.a
    - CRT/*.o
    - CRT/*.opp

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update -qq
  - >
      apt-get install -y -qq \
        coreutils wget tar gzip bzip2 patch cmake make binutils gcc g++ autoconf automake flex bison texinfo \
        git subversion curl xz-utils osslsigncode

makedeps:
  script:
    - if [ "x${FORCE_TOOLCHAIN_REBUILD:-}" != "x" ]; then rm -rf w64-mingw32-sysroot/; fi
    - pwd
    - >
        { test -x w64-mingw32-sysroot/x86_64/bin/x86_64-w64-mingw32-gcc && \
          test -x w64-mingw32-sysroot/x86_64/bin/x86_64-w64-mingw32-g++ && \
          test -r CRT/kcrt.opp && \
          test -r EASTL-build/libEASTL.a && \
          test -r EASTL-native-build/libEASTL.a; } || \
        { make deps JOBS=${BUILDJOBS:-4} Q= || { cat bld/build.log; false; }; }
  stage: deps
  only:
    - master

makedeps-again:
  script:
    - git clean -df .
    - git clean -dfX .
    - git checkout .
    - make deps JOBS=${BUILDJOBS:-4} Q= || { cat bld/build.log; false; }
  stage: deps
  only:
    - master
  when: manual

build:
  script:
    - make help
    - make help BUILD_NATIVE=1
    - ls -alh w64-mingw32-sysroot/x86_64/
    - ls -alh w64-mingw32-sysroot/x86_64/bin/
    - pwd
    - mkdir -p ./mingw-w64-build && touch ./mingw-w64-build/mingw-w64-build
    - touch -m ./w64-mingw32-sysroot/x86_64/bin/x86_64-w64-mingw32-gcc
    - make -j1 all WERROR=1 Q=
    - make -j1 install WERROR=1 Q= DESTDIR=_install
    - ls -alh _install
  artifacts:
    expire_in: 1 week
    paths:
      - _install/
  stage: build
  only:
    - master
  dependencies:
    - makedeps
