version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:jammy
    steps:
      - checkout
      - run: export DEBIAN_FRONTEND=noninteractive
      - run: apt-get update -qq
      - run: |
          env DEBIAN_FRONTEND=noninteractive \
          apt-get install -y -qq \
          coreutils wget tar gzip bzip2 patch cmake make binutils gcc g++ autoconf automake flex bison texinfo \
          git subversion curl xz-utils osslsigncode \
          binutils-mingw-w64-x86-64 gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 mingw-w64-x86-64-dev
      - run: |
          make deps \
            WERROR=1 JOBS=4 Q= \
            LOCAL_MINGW64_CC=/usr/bin/x86_64-w64-mingw32-gcc \
            LOCAL_MINGW64_CXX=/usr/bin/x86_64-w64-mingw32-g++ \
            LOCAL_MINGW64_RC=/usr/bin/x86_64-w64-mingw32-windres \
            LOCAL_MINGW64_AR=/usr/bin/x86_64-w64-mingw32-ar \
            DDK_INCLUDE_DIR=/usr/x86_64-w64-mingw32/include/ddk
      - run: |
          test -r EASTL-build/libEASTL.a
      - run: |
          make examples \
            WERROR=1 JOBS=4 Q= \
            LOCAL_MINGW64_CC=/usr/bin/x86_64-w64-mingw32-gcc \
            LOCAL_MINGW64_CXX=/usr/bin/x86_64-w64-mingw32-g++ \
            LOCAL_MINGW64_RC=/usr/bin/x86_64-w64-mingw32-windres \
            LOCAL_MINGW64_AR=/usr/bin/x86_64-w64-mingw32-ar \
            DDK_INCLUDE_DIR=/usr/x86_64-w64-mingw32/include/ddk \
            DESTDIR=$(realpath _install)
          make examples-install Q= \
            DESTDIR=$(realpath _install)
      - run: |
          test -r _install/codesign-ca-cert.crt -a \
               -r _install/dpp-example.bat -a \
               -r _install/dpp-example-cplusplus.bat -a \
               -r _install/dpp-example-cplusplus-EASTL.bat -a \
               -r _install/dpp-example.sys -a \
               -r _install/dpp-example-cplusplus.sys -a \
               -r _install/dpp-example-cplusplus-EASTL.sys
      - run: |
          ./examples/dpp-example-cplusplus-EASTL.run
      - run: |
          wget 'https://github.com/utoni/mingw-w64-build-ng/releases/download/v1.0/mingw-w64-toolchain.tbz2' -O ./mingw-w64-toolchain.tbz2
      - run: |
          make examples-clean
      - run: |
          make deps-distclean
      - run: |
          make deps \
            WERROR=1 JOBS=4 Q= \
            USE_MINGW64_TARBALL=./mingw-w64-toolchain.tbz2
